services:
  db:
    image: postgres:latest
    container_name: protocol_container
    environment:
      POSTGRES_USER: protocol_server
      POSTGRES_PASSWORD: server-pwd
      POSTGRES_DB: protocols
    ports:
      - "5800:5432"
    volumes:
      - db_data:/var/lib/postgresql/protocols/data

volumes:
  db_data: