services:
  vosk-server-de:
    image: alphacep/kaldi-de:latest
    container_name: vosk-api-server
    ports:
      - "2700:2700"
    restart: always
  db:
    image: postgres:latest
    container_name: protocol_container
    environment:
      POSTGRES_USER: ${protocol_server}
      POSTGRES_PASSWORD: ${database_server_pwd}
      POSTGRES_DB: ${protocol_db_name}
    ports:
      - "${db_port}:5432"
    volumes:
      - db_data:/var/lib/postgresql/protocols/data

volumes:
  db_data: