services:
  vosk-server-de:
    image: alphacep/kaldi-de:latest
    container_name: vosk-api-server
    ports:
      - "2700:2700"
    restart: always

  db:
    image: postgres:latest
    container_name: protocol_container
    environment:
      POSTGRES_USER: ${user_name}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${db_name}
    ports:
      - "${port}:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/protocols/data

  protogen_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protogen_backend
    environment:
      - FLASK_ENV=development
      - VOSK_HOST_URI=vosk-server-de
    ports:
      - "5000:5000"
    depends_on:
      - db
      - vosk-server-de
    volumes:
      - ./:/usr/src/app

volumes:
  db_data: