version: '3.8'

services:
  vosk-server:
    image: alphacep/kaldi-de:latest
    container_name: vosk-api-server
    ports:
      - "2700:2700"
    restart: always  # Automatically restart on failure
  ollama:
    image: ollama/ollama:latest
    ports:
      - "7869:11434"
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0