name: Deploy ProtoGen-be

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      CLIENT_SECRETS: ${{ secrets.CLIENT_SECRETS }}
      DATABASE_METADATA: ${{ secrets.DATABASE_METADATA }}
      PYANNOTE_KEY: ${{ secrets.PYANNOTE_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check and create virtual environment
        run: |
          if [ ! -d ".venv" ]; then
            echo "Creating virtual environment in .venv folder"
            python -m venv .venv
          else
            echo "Virtual environment already exists, skipping creation"
          fi

      - name: update requirements
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip       
          pip install -r requirements.txt

      - name: Import Secrets
        run: |
          echo "$CHATGPT_API_KEY" > .venv/CHATGPT_API
          echo "$CLIENT_SECRETS" > .venv/client_secrets.json
          echo "$DATABASE_METADATA" > .venv/database_metadata.json
          echo "$PYANNOTE_KEY" > .venv/PYANNOTE_KEY

      - name: Restart Containers
        run: |
          if [ "$(docker ps -q -f name=protogen_backend)" ]; then
            docker kill protogen_backend
            docker rm protogen_backend
            docker build -t protogen_backend .
            docker run -d protogen_backend
          else
            ./restart_docker.sh
          fi